### ISSUE TITLE
Getting Started Brainstorm 

### ISSUE THREAD

**Issue by haileypate** [cityofaustin/open-data-suggestions#12]
Hey @cityofaustin/suggestion-workflow-team, 

What do you think of the workflow diagram [here](https://docs.google.com/drawings/d/1Q0DrMlVF4zY2Oj5kkvizOgQRyKDhAzk7hgvxnMQ2k5w/edit?usp=sharing)?

When you review the workflow diagram, what ideas/questions/to-do-items come to mind?

Feel free to add comments below! I'll organize all of the feedback for us to review together at our next meeting.

**Comment by haileypate** [comment]
Here are some of the thoughts that came out of our kickoff meeting: 
- How will people know which departments to send their suggestions to?
- How exactly do these suggestions relate to Public Information Requests (PIRs)?
- When suggestions arrive, what other guidance can we provide beyond just a dataset? Could the customer need be better addressed by raw data or by a visualization?
- Should we/could we provide a way to “plus one” dataset suggestions?

**Comment by CodeMcConnell** [comment]
Providing an upvote affordance would reinforce the idea that open data (rocks and) is a common resource, rather than a service provided to individual requestors. It would also provide a basis by which datasets could be prioritized if the city doesn't develop an SLA-like protocol for responding to requests.

**Comment by johnclary** [comment]
Nice work on the diagram. Ideally there would be customer contact at each step in the workflow, or, if not direct contact, a means for the customer to see the status of their suggestion as it moves through the review process. 

Also, a case is missing from the workflow where we receive a data suggestion that has already been suggested in the past.

**Comment by haileypate** [comment]
@johnclary Agreed, that touchpoint between customer at staff and each step seems critical for keeping things open and moving forward. 

I made some interim adjustments to the workflow diagram to try accounting for the "repeat suggestion" use case. 

Also, I added a box to account for when someone "upvotes" an existing suggestion to help us account for  that type of input from users.

**Comment by haileypate** [comment]
closing out, will still be available review in archive if needed
