### ISSUE TITLE
link to current draft of use case specification

### ISSUE THREAD

**Issue by haileypate** [cityofaustin/open-data-suggestions#15]
Rob Byrd has delivered the first draft of our use case specification! 

It can be found here: 
http://austinea.org/arch/pir/requestSuggestedModifiedDataSet/

@cityofaustin/suggestion-workflow-team, What do you think of the first draft? Feel free to add thoughts/comments to this thread.

**Comment by cronins** [comment]
I think it captures what all we talked about. Looks good!

**Comment by haileypate** [comment]
### Meeting notes, 12 Apr 2016:
- We added some steps in the manageOpenCollaboration task... when a dataset request is submitted, the request will enter a queue (visible to the public) where it awaits intake staff review. After review, the request may become available for comment, community upvoting, etc. 
- How does 311 know which department to contact when an issue comes in? Do they have any cheat sheets to share with us? Potential person to contact about this would be Patty Mendez.
- Added last function uploadDataSet
- Rob is going to add language about the system notifications that happen

**Comment by haileypate** [comment]
Hi @cityofaustin/suggestion-workflow-team, the latest version of the spec is now available! Please take a moment to review and add comments/suggestions to the [issues](https://github.com/cityofaustin/open-data-suggestions/issues) list for discussion. Thanks!

**Comment by haileypate** [comment]
add a link to this document in the readme here: https://github.com/cityofaustin/open-data-suggestions
