### ISSUE TITLE
develop a form that doesn't require github login

### ISSUE THREAD

**Issue by haileypate** [cityofaustin/open-data-suggestions#5]
https://gitreports.com/tutorial

thanks @luqmaan!

**Comment by mateoclarke** [comment]
Some more resources on this issue making it less intimidating for newbies:

[Hacking GitHub: 12 simple tools to help introduce open source to the uninitiated](http://ben.balter.com/2015/01/11/hacking-github/)

[Problem Child Ruby Gem](https://github.com/benbalter/problem_child)

> Allows authenticated or anonymous users to fill out a standard web form to create GitHub issues (and pull requests).
